version: "3"

services:
  database:
    platform: linux/x86_64
    image: mysql:8.0.25
    ports:
      - "3306:3306"
    networks:
      - counter_network
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: mysql8.0.25
    volumes:
      - counter_database:/var/lib/mysql
  counter_app:
    build:
      context: ../..
      dockerfile: ./docker/development/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - counter_network
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_NAME: counter_dev
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: mysql8.0.25
    depends_on:
      - database

volumes:
  counter_database:

networks:
  counter_network:
    driver: bridge
